### ISSUE TITLE
Running Hybracter on Intel Mac - Medaka v2.0 won't install

### ISSUE THREAD

**Issue by suzumar** [gbouras13/hybracter#112]
Hello

I am trying to install version 0.11 on an intel mac and somehow I cannot finish installation without having medaka 2.0 which only has been deployes in conda for amd ...  Is there any way to work around it?  I guess I can run medaka 1.11 separately but I would prefer to run it with hybracter if possible

Thanks

**Comment by gbouras13** [comment]
Hi @suzumar ,

Are you using the flag `--mac` in your installation ? That should solve the issue and install medaka v1.8 (this is not too different from v1.11, which causes a lot of installation pain in CI tests).

Alternatively, you could use the docker container option that I have just added better documentation for thanks to this issue - it should let you run Medaka v2 as well.

George




George

**Comment by suzumar** [comment]
Hi, I was able to install with the --mac, `sudo hybracter install --mac -d /work/databases/hybra` but I unfortunately still get the medaka error at running time.  I will try with the docker image.

**Comment by gbouras13** [comment]
@suzumar can you try using —mac at runtime too? Eg hybracter hybrid —mac or whatever.

george

**Comment by suzumar** [comment]
Thanks ! That seems to work, I tried it before but I put the option too early in the command (before long-single) it seems to be working now.

**Comment by gbouras13** [comment]
No problems glad it worked! Closing this issue now
